- name: ATARI Git repository
  git:
    repo: 'https://github.com/epfl-si/atari'
    dest: /srv/atari/build
    version: "master"
    force: yes

- name: Build and push ATARI image
  register: _atari_image
  community.docker.docker_image:
    name: "{{ atari_image_name }}"
    push: true
    source: build
    force_source: yes
    build:
      path: /srv/atari/build
